// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvIUljgTZONQ-5Z9rVf1kXujmEa4Bth9w',
    appId: '1:462202234211:web:84c0115718aef6c6279f56',
    messagingSenderId: '462202234211',
    projectId: 'app-hui-a0fa1',
    authDomain: 'app-hui-a0fa1.firebaseapp.com',
    storageBucket: 'app-hui-a0fa1.firebasestorage.app',
    measurementId: 'G-H8T1GWY6NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ziGyUJfoRZNmSNmqo5Tn-WHIOpyLtY8',
    appId: '1:462202234211:android:8d54cb5b06e92b05279f56',
    messagingSenderId: '462202234211',
    projectId: 'app-hui-a0fa1',
    storageBucket: 'app-hui-a0fa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoJ_diQAHNU6obW3GBoh7yjTqTgsLWfyg',
    appId: '1:462202234211:ios:5aaa45f3f82ede6b279f56',
    messagingSenderId: '462202234211',
    projectId: 'app-hui-a0fa1',
    storageBucket: 'app-hui-a0fa1.firebasestorage.app',
    iosBundleId: 'com.example.huiApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoJ_diQAHNU6obW3GBoh7yjTqTgsLWfyg',
    appId: '1:462202234211:ios:5aaa45f3f82ede6b279f56',
    messagingSenderId: '462202234211',
    projectId: 'app-hui-a0fa1',
    storageBucket: 'app-hui-a0fa1.firebasestorage.app',
    iosBundleId: 'com.example.huiApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvIUljgTZONQ-5Z9rVf1kXujmEa4Bth9w',
    appId: '1:462202234211:web:392977dd33a4e1f9279f56',
    messagingSenderId: '462202234211',
    projectId: 'app-hui-a0fa1',
    authDomain: 'app-hui-a0fa1.firebaseapp.com',
    storageBucket: 'app-hui-a0fa1.firebasestorage.app',
    measurementId: 'G-NFJL3M10Y5',
  );
}
